apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: docbrown-statestore
  namespace: docbrown
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
  - name: actorStateStore
    value: "true"
scopes:
 - docbrown.app.server
 - docbrown.forecaster.api
 - docbrown.service.dataloade 