version: '3.4'

services:

  redis:
    image: redis:alpine


  zipkin:
    image: openzipkin/zipkin-slim:latest
    ports:
      - "5411:9411"

  docbrown.app.server:
    image: ${DOCKER_REGISTRY-}docbrown.app.server
    build:
      context: .
      dockerfile: DocBrown.App/Server/Dockerfile
    depends_on:
      - redis

  docbrown.app.server-dapr:
    image: "daprio/dapr:latest"
    network_mode: "service:docbrown.app.server"
    depends_on:
      - docbrown.app.server

  docbrown.forecaster.api:
    image: ${DOCKER_REGISTRY-}docbrown.forecaster.api
    build:
      context: .
      dockerfile: DocBrown.Forecaster.API/Dockerfile
    depends_on:
      - redis

  docbrown.forecaster.api-dapr:
    image: "daprio/dapr:latest"
    network_mode: "service:docbrown.forecaster.api"
    depends_on:
      - docbrown.forecaster.api


  docbrown.service.dataloader:
    image: ${DOCKER_REGISTRY-}docbrownservicedataloader
    build:
      context: .
      dockerfile: DocBrown.Service.DataLoader/Dockerfile
    depends_on:
      - redis

  docbrown.service.dataloader-dapr:
    image: "daprio/dapr:latest"
    network_mode: "service:docbrown.service.dataloader"
    depends_on:
      - docbrown.service.dataloader

  docbrown.basket.purchase:
    image: ${DOCKER_REGISTRY-}docbrownbasketpurchase
    build:
      context: .
      dockerfile: DocBrown.Basket.Purchase/Dockerfile
    depends_on:
     - redis

  docbrown.basket.purchase-dapr:
    image: "daprio/dapr:latest"
    network_mode: "service:docbrown.basket.purchase"
    depends_on:
      - docbrown.basket.purchase


