version: '3.4'

services:

  redis:
    ports:
      - "5379:6379"

  zipkin:
    ports:
      - "5411:9411"

  docbrown.app.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "51000:50001"
      - "80"

  docbrown.app.server-dapr:
    command: [ 
        "./daprd",
        "-app-id", "app-server",
        "-app-port", "80",
        "-components-path", "/components",
        ]
    volumes:
      - "./dapr/components/:/components"


  docbrown.forecaster.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
      - "52000:50001"


  docbrown.forecaster.api-dapr:
    command: [ 
        "./daprd", 
        "-app-id", "forecast-service",
        "-app-port", "80",
        "-components-path", "/componentes",
       ]
    volumes:
      - "./dapr/components/:/components"
    

  docbrown.service.dataloader:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
      - "53000:50001"

  docbrown.service.dataloader-dapr:
    command: [ 
        "./daprd", 
        "-app-id", "dataloader-service",
        "-app-port", "80",
        "-components-path", "/components",
       ]
    volumes:
     - "./dapr/components/:/components"

  docbrown.basket.purchase:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  docbrown.basket.purchase-dapr:
    command: [ 
        "./daprd", 
        "-app-id", "basket-service",
        "-app-port", "80",
        "-components-path", "/components",
       ]
    volumes:
     - "./dapr/components/:/components"





