version: '3.4'

services:

  redis:
    image: redis:alpine possivel
    ports: 
      - "6379:6379"

  docbrown.app.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  docbrown.forecaster.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  docbrown.service.dataloader:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

