version: '3.4'

services:
  docbrown.app.server:
    image: ${DOCKER_REGISTRY-}docbrown.app.server
    build:
      context: .
      dockerfile: DocBrown.App/Server/Dockerfile
    ports:
      - "51000:50001"
  docbrown.app.server-dapr:
    image: "daprio/dapr:latest"
    command: [ 
        "./daprd", 
        "-app-id", 
        "docbrownserver", 
        "-app-port", 
        "80",
        "-components-path", "/components",
        "-config", "/configuration/docbrown-config.yaml"
        ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    depends_on:
      - docbrown.app.server
    network_mode: "service:docbrown.app.server"

  docbrown.forecaster.api:
    image: ${DOCKER_REGISTRY-}docbrown.forecaster.api
    build:
      context: .
      dockerfile: DocBrown.Forecaster.API/Dockerfile
    ports:
     - "52000:50001"
  docbrown.forecaster.api-dapr:
    image: "daprio/dapr:latest"
    command: [ 
        "./daprd", 
        "-app-id", 
        "docbrownforecasterapi", 
        "-app-port", 
        "80",
        "-components-path", "/components",
        "-config", "/configuration/docbrown-config.yaml"
       ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    depends_on:
      - docbrown.forecaster.api
    network_mode: "service:docbrown.forecaster.api"

