version: '3.4'

services:
  docbrown.app.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  docbrown.forecaster.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

